title: Berlin Kraft Soda Lab
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2544803
  brandStrength: 0.5625
  lightness: 0.75
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.9874552
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: sodakraft
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 1
