name: sodakraft
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Berlin Kraft Soda Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.5551070861984044
  rhythmicContrast: 0.5851114368997514
purpose: []
